server:
  name: droolsServer
  port: 8091

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drools?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: 5587396lj
    maxIdleTime: 60
    maxPoolSize: 50
    idleConnectionTestPeriod: 18000
    initialPoolSize: 3
    minPoolSize: 3
    preferredTestQuery: select 1
    acquireIncrement: 2

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.server.model
  multipleResultSetsEnabled: true
  defaultExecutorType: REUSE
  defaultStatementTimeout: 30
  useColumnLabel: true
  lazyLoadingEnabled: true
  config-location: classpath:mybatis-config.xml

logging:
  level:
    org.springframework: ERROR
    com.server: DEBUG
    org.jboss.netty: DEBUG
    org.kie: ERROR
    org.apache: ERROR

netty:
  server:
    name: droolsServerSocket
    port: 8092
    readTime: 20
    writeTime: 20
    idleTime: 25
    idleReadTime: 20
    idleWriteTime: 20
    timeout: 10000
  bueffer:
    maxFrameLength: 2147483647
    lengthFieldOffset: 0
    lengthFieldLength: 4
    lengthAdjustment: 0
    initialBytesToStrip: 4

droolsconfig:
  kieBaseconfiguration:
    multithreadevaluation: true
    maxthreads: 20